CREATE TABLE schema_version
(
    patch_level      SMALLINT PRIMARY KEY,
    patch_file       TEXT,
    created_datetime TIMESTAMPTZ DEFAULT current_timestamp
);

CREATE TABLE users
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  TEXT NOT NULL UNIQUE,
    password  BYTEA,
    firstname TEXT,
    lastname  TEXT
);

CREATE TABLE watch_lists
(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT UNIQUE NOT NULL
);

INSERT INTO watch_lists(url)
VALUES ('https://www.willhaben.at/iad/immobilien/haus-kaufen/haus-angebote?isNavigation=true&areaId=601&areaId=603&areaId=606&areaId=616'),
       ('https://www.willhaben.at/iad/immobilien/eigentumswohnung/eigentumswohnung-angebote?isNavigation=true&areaId=601');

CREATE TABLE user_watch_list
(
    user_id       SMALLINT REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    watch_list_id SMALLINT REFERENCES watch_lists (id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (user_id, watch_list_id)
);


CREATE TABLE contents
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash TEXT  NOT NULL,
    raw  JSONB NOT NULL
);

CREATE TABLE data_blocks
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp  TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    content_id INT         NOT NULL REFERENCES contents (id) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE (timestamp, content_id)
);

CREATE TABLE attributes
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute TEXT NOT NULL UNIQUE
);

CREATE TABLE content_attributes
(
    data_block_id INT NOT NULL REFERENCES data_blocks (id) ON DELETE CASCADE ON UPDATE CASCADE,
    attribute_id  INT NOT NULL REFERENCES attributes (id) ON DELETE CASCADE ON UPDATE CASCADE,
    values        TEXT[],
    PRIMARY KEY (data_block_id, attribute_id)
);

CREATE TYPE LOCATION_STATE AS ENUM (
    'INITIAL',
    'USER_DEFINED',
    'CALCULATED'
    );

CREATE TABLE locations
(
    content_id  INT PRIMARY KEY REFERENCES contents (id) ON DELETE CASCADE ON UPDATE CASCADE,
    state       LOCATION_STATE NOT NULL DEFAULT 'INITIAL',
    coordinates POINT,
    house_nr    TEXT,
    street      TEXT,
    city        TEXT,
    postal_code INT
);

