CREATE TABLE schema_version
(
    patch_level      SMALLINT PRIMARY KEY,
    patch_file       TEXT,
    created_datetime TIMESTAMPTZ DEFAULT current_timestamp
);

CREATE TABLE users
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  TEXT NOT NULL UNIQUE,
    password  BYTEA,
    firstname TEXT,
    lastname  TEXT
);

CREATE TABLE watch_lists
(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT UNIQUE NOT NULL
);

CREATE TABLE user_watch_list
(
    user_id       SMALLINT REFERENCES users (id)       NOT NULL,
    watch_list_id SMALLINT REFERENCES watch_lists (id) NOT NULL,
    PRIMARY KEY (user_id, watch_list_id)
);

CREATE TABLE pages
(
    id        INT         NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    hash      BYTEA GENERATED ALWAYS AS ( digest(raw, 'sha256') ) STORED,
    raw       TEXT        NOT NULL,
    PRIMARY KEY (id, timestamp)
);
