server:
  host: 0.0.0.0
  port: 9191

database:
  host: localhost
  name: willhaben
  user: willhaben
  password: willhaben
  admin:
    user: postgres
    password: postgres

logger:
  level: INFO
  appenders:
    - type: console
      filters:
        - all #lowercase!

crawler:
  timeout: 1800 # 30 * 60 seconds
  #debugAmount: 30
