server:
  host: 127.0.0.1
  port: 9191

database:
  host: localhost
  name: willhaben
  user: willhaben
  password: willhaben
  admin:
    user: postgres
    password: postgres


crawler:
  interval:
    - 60 # Minutes
    - 180 # Minutes

logger:
  level: INFO
  appenders:
    - type: console
      filters:
        - all #lowercase!
